apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-nfs-storage-pvc1
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
