---
apiVersion: v1
kind: Pod
metadata:
  name: hello-blacklistimages
spec:
  containers:
  - image: docker.io/library/busybox
    imagePullPolicy: IfNotPresent
    name: hello
    command: [ "sh", "-c", "echo 'Hello blacklistimages!' && sleep 1h" ]