apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor
  # RuntimeClass is a non-namespaced resource
handler: runsc  # The name of the corresponding CRI configuration

# kubectl run gvisor-test --image=nginx:1.19.2 --dry-run=client -o yaml > /tzhong/nginx.yaml
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gvisor-test
  name: gvisor-test
spec:
  nodeName: ubuntu-k8s-node1 # add
  runtimeClassName: gvisor   # add
  containers:
  - image: nginx:1.19.2
    name: gvisor-test
