---
apiVersion: v1
kind: Namespace
metadata:
  name: team-green

---
apiVersion: v1
kind: Secret
metadata:
  name: database-access
  namespace: team-green
type: Opaque 
stringData:
  pass: confidential