---
apiVersion: v1
kind: Secret
metadata:
  name: adam-server-secret-tls
  namespace: ingress-nginx
data:
  # 使用命令`cat adam-server.crt | base64 -w 0`生成 base64 encoded cert
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzRENDQWNRQ0NRQ2VUSG1TVVVhMnREQU5CZ2txaGtpRzl3MEJBUXNGQURDQmdERUxNQWtHQTFVRUJoTUMKUTA0eEVUQVBCZ05WQkFnTUNGTm9ZVzVuYUdGcE1SRXdEd1lEVlFRSERBaFRhR0Z1WjJoaGFURVVNQklHQTFVRQpDZ3dMVFdsamNtOGdSbTlqZFhNeEV6QVJCZ05WQkFNTUNuUjZhRzl1Wnk1amIyMHhJREFlQmdrcWhraUc5dzBCCkNRRVdFWFI2YUc5dVowQjBlbWh2Ym1jdVkyOXRNQjRYRFRJd01URXlOVEV6TWpZeE9Gb1hEVEl4TVRFeU5URXoKTWpZeE9Gb3dZekVMTUFrR0ExVUVCaE1DUTA0eEVUQVBCZ05WQkFnTUNGTm9ZVzVuYUdGcE1SRXdEd1lEVlFRSApEQWhUYUdGdVoyaGhhVEVVTUJJR0ExVUVDZ3dMVFdsamNtOGdSbTlqZFhNeEdEQVdCZ05WQkFNTUQyRmtZVzB1CmRIcG9iMjVuTG1OdmJUQ0JuekFOQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUFzbjd5MDBXTmJFTmkKdHVjWFpJZHg4WU9qWDU4NW1HUFZQWlREWjkxaDBZa1lYM3BvdUIrY2ZFMG1PZ0FZaWg3R05Pa3A4bUV6MmFyegpJRWJEc3FDZnZBUjk2NTg5QmVGQWQrMWJydzFNK3FtWlNOdXhid1R4VGd0YmxGa0FzNHVHSlVsdEJ1VkMxZmZXClN2bTlFQnpFMWtreHVWTEtZR3dEQ2hIeGRuNDBwWXNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKZklaVitYK3hhOVBld2RFTFV1SmlkZXp1MnowelNDQ0lmMmY1U3JaT0sxVWRueGlyMUQvblpwWUVPY3daYlVwYgpWamFVdDNSRzJqU3dCTCtWbkZMdWlzb01uU0J4UU1ySVlmTzhUa1pPL0Ntamp3SFFtOEJMZUppZ05YSjVPOTZ5CjBxWksvZlNIUFdUSkdLZmRpWHVOVWVEU3lYOWc5Y1lRbXBGa0lacmtWKzAwaG5hR3lmb2RFcnA4MEdiSFFNUjYKNDhWWk1pSzgvWk1aQTduamhndVVwbk9xRUFLaEZwVUdQRFViWnh1YmRiS2IyZ2tDb1JOdFZiditWY3BtRlBregpjOU9WdEhEZ001OEJ6Vkl1RlIydEgvOFIxNzRnN2Fzdk5VemtGS3NkS0ZDUmo2a3B2ZnFxcGE0eFBMTThHa1JTCk00aEtaZ0pZbzVaaUM2WGVrL3lNdmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  # 使用命令`cat adam-server.key | base64 -w 0`生成 base64 encoded key
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWHdJQkFBS0JnUUN5ZnZMVFJZMXNRMksyNXhka2gzSHhnNk5mbnptWVk5VTlsTU5uM1dIUmlSaGZlbWk0Ckg1eDhUU1k2QUJpS0hzWTA2U255WVRQWnF2TWdSc095b0orOEJIM3JuejBGNFVCMzdWdXZEVXo2cVpsSTI3RnYKQlBGT0MxdVVXUUN6aTRZbFNXMEc1VUxWOTlaSytiMFFITVRXU1RHNVVzcGdiQU1LRWZGMmZqU2xpd0lEQVFBQgpBb0dCQUptQ2VuM2V4RmtHdnlBRU1PY2hZWXBQSnpOMnNjYnduUlVnR3NuNTZFV1h2V0ZuMmlYMzhkSXBXNlhvCkxUS2tjdHhRWnVYd1dQSnJoanNOQVFOZ0J0N3gzb2xBVHlHWCtJNDVxOFhXN3J4N2JZdjN4VVVielpBcWZ2dXoKN2tLaFJFSGk5VUw5YWxKNVFoZ3lrVi9TQmtHVWxUbUNkNHNFZFdZMVprejJoK1NSQWtFQTE2Vmg2K05MWHdoYwo2NGhSamsxRnYxbEplWkhNOGY4V2NveWptYkY0LzMyK2VZcGJDQktURDVSQmNsYmZjZ0gzZXVXV1NKcXJyVzUzCmNURkl4V3N4QXdKQkFOUGwzMlB5SE5aeDhUaEdaZFlsMjRWc0c0bWlHMVRDMDRPUzZzc0wwR0ZWaUc1TTJGWUoKSnB1b3lMSzMwa3Zlb3lYSUVJY3VmSkNLZCtZMWdFSnpYdGtDUVFDN2IrREJLL3RqU3QyWlRBKzNaS3J2T3lpRwpKcGpBN3p3UHJQYTJyRy9EZ3dTQW1DV3Z5cFZRd1VoeG5kanlPNHRrb3hJUllYOC9hL2tkeGZ5K3ZBRUpBa0VBCnhJVkVLbUNJYUVaaWptdVQxUWxsVDVlVTdvKyt3MXl4YUN5Z3YxR2tvREVBaURPU3pEQk9jejBWYmRMWUllOUkKNWloblU4aEVWSlZuWDhVc3YvUlorUUpCQU1BbThMUmU5NXhib2w4RnhIQWxvcFhuWjZZaWM1V1dOSVB3ZHFhWQpXRkJ6QkRSVGVHdk8rWE83ak5od3BLaFlRWEtWVm9EaXRNZG9Yb2k3NStTQUNzYz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls

---
# For k8s 1.18
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: adam-server-tls-ingress
#   namespace: ingress-nginx
# spec:
#   ingressClassName: nginx
#   tls:
#   - hosts:
#       - adam.tzhong.com
#     secretName: adam-server-secret-tls
#   rules:
#   -  host: adam.tzhong.com
#      http: 
#       paths:
#       - backend:
#           serviceName: nginx-svc
#           servicePort: 80
---
# For k8s 1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adam-server-tls-ingress
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - adam.tzhong.com
    secretName: adam-server-secret-tls
  rules:
  - host: adam.tzhong.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80