---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: unprivileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: false
#  hostPorts:
#  - min: 0
#    max: 65535
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: 'MustRunAs'
    ranges:
    - max: 1999
      min: 1999
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
    - max: 1999
      min: 1999
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - max: 1999
      min: 1999
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - max: 1999
      min: 1999
  
