apiVersion: v1
kind: Pod
metadata:
  name: nginx-security-pod
  labels:
    app: web
spec:
  hostNetwork: false
  hostIPC: false
  hostPID: false
  containers:
  - name: nginx
    image: nginx 
    securityContext:
      privileged: false
      capabilities:
        add: ["NETWORK_ADMIN"]
      readOnlyRootFilesystem: true 
      runAsUser: 100
      runAsGroup: 1000