---
apiVersion: v1
kind: Pod
metadata:
  name: hello-without-apparmor
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: hello
    command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]