---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-use-emptydir
spec:
  containers:
    - image: nginx:1.19.4
      name: nginx
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
      
---        
apiVersion: v1
kind: Pod
metadata:
  name: nginx-use-hostpath
spec:
  containers:
  - image: nginx:1.19.4
    name: nginx
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /mnt
      # this field is optional
      type: Directory