apiVersion: v1
kind: Pod
metadata:
  name: nginx-shared-volume
spec:
  containers:
  - image: nginx:1.19.4
    name: nginx
    command: ["/bin/sh", "-c", "touch /var/log/nginx/access.log && \
        touch /var/log/nginx/access.log && \
        nginx -g 'daemon off;'"]
    # command: ["/bin/sh", "-c", "while :; do echo '.'; sleep 100000 ; done"]
    volumeMounts:
    - mountPath: /var/log/nginx
      name: shared-volume
  - image: busybox:1.32.0
    name: busybox
    command: ["/bin/sh", "-c", "tail -f /var/log/nginx/access.log"]
    volumeMounts:
    - mountPath: /var/log/nginx
      name: shared-volume
  volumes:
  - name: shared-volume
    emptyDir: {}


# kubectl create -f ./nginx-shared-volume.yaml
# kubectl exec -it nginx-shared-volume -c nginx -- curl http://localhost:80/
# kubectl logs nginx-shared-volume -c busybox